import { zodResolver } from '@hookform/resolvers/zod';
import { Calendar, Loader2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { Button } from './ui/button';
import type { Project, ProjectInput } from '@/types';

const schema = z.object({
  name: z.string().min(2,'Name must be at least 2 characters').max(120),
  description: z.string().max(2000).optional(), location: z.string().max(160).optional(), category: z.string().max(80).optional(),
  status: z.enum(['PLANNING','ACTIVE','COMPLETED','ARCHIVED']), startDate: z.string().min(1,'Start date is required'), endDate: z.string().optional(), coverImage: z.union([z.url('Use a valid URL'),z.literal('')]).optional(),
}).refine(v=>!v.endDate||v.endDate>=v.startDate,{message:'End date must be after the start date',path:['endDate']});
type FormData=z.infer<typeof schema>;

const categories=['Conservation','Clean water','Reforestation','Renewable energy','Community development','Education','Public health','Other'];
export function ProjectForm({ project, onSubmit, submitLabel='Create project' }: { project?:Project; onSubmit:(input:ProjectInput)=>Promise<void>; submitLabel?:string }) {
  const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{name:project?.name||'',description:project?.description||'',location:project?.location||'',category:project?.category||'',status:project?.status||'PLANNING',startDate:project?.startDate?.slice(0,10)||new Date().toISOString().slice(0,10),endDate:project?.endDate?.slice(0,10)||'',coverImage:project?.coverImage||''}});
  const submit=(v:FormData)=>onSubmit({...v,startDate:new Date(v.startDate).toISOString(),endDate:v.endDate?new Date(v.endDate).toISOString():null,description:v.description||null,location:v.location||null,category:v.category||null,coverImage:v.coverImage||null});
  return <form onSubmit={handleSubmit(submit)} className="card p-5 md:p-7"><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label className="label" htmlFor="project-name">Project name</label><input id="project-name" className="field" placeholder="e.g. Western Ghats Watershed Revival" {...register('name')}/>{errors.name&&<p className="mt-1.5 text-xs text-red-600">{errors.name.message}</p>}</div><div className="md:col-span-2"><label className="label" htmlFor="project-description">Description</label><textarea id="project-description" className="field min-h-28 resize-y" placeholder="What is this project working to change?" {...register('description')}/></div><div><label className="label" htmlFor="project-location">Location</label><input id="project-location" className="field" placeholder="District, state or country" {...register('location')}/></div><div><label className="label" htmlFor="project-category">Category</label><select id="project-category" className="field" {...register('category')}><option value="">Select a focus area</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label" htmlFor="project-status">Status</label><select id="project-status" className="field" {...register('status')}><option value="PLANNING">Planning</option><option value="ACTIVE">Active</option><option value="COMPLETED">Completed</option><option value="ARCHIVED">Archived</option></select></div><div><label className="label" htmlFor="project-cover">Cover image URL <span className="normal-case tracking-normal text-stone/60">(optional)</span></label><input id="project-cover" className="field" placeholder="https://…" {...register('coverImage')}/>{errors.coverImage&&<p className="mt-1.5 text-xs text-red-600">{errors.coverImage.message}</p>}</div><div><label className="label" htmlFor="project-start-date">Start date</label><div className="relative"><Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-stone" size={16}/><input id="project-start-date" type="date" className="field pl-10" {...register('startDate')}/></div>{errors.startDate&&<p className="mt-1.5 text-xs text-red-600">{errors.startDate.message}</p>}</div><div><label className="label" htmlFor="project-end-date">End date <span className="normal-case tracking-normal text-stone/60">(optional)</span></label><div className="relative"><Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-stone" size={16}/><input id="project-end-date" type="date" className="field pl-10" {...register('endDate')}/></div>{errors.endDate&&<p className="mt-1.5 text-xs text-red-600">{errors.endDate.message}</p>}</div></div><div className="mt-7 flex justify-end"><Button disabled={isSubmitting}>{isSubmitting&&<Loader2 size={17} className="animate-spin"/>}{submitLabel}</Button></div></form>;
}
